version: '3.8'
services:
  db:
    image: postgres:16
    container_name: construction_db_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin # Tên đăng nhập DB
      POSTGRES_PASSWORD: admin # Mật khẩu DB
      POSTGRES_DB: construction_db # Tên Database sẽ tự tạo
    volumes:
      - postgres_data:/var/lib/postgresql/data # Để giữ dữ liệu không bị mất khi tắt Docker

volumes:
  postgres_data:
